### ISSUE TITLE
2019 July release

### ISSUE THREAD

**Issue by aewallin** [aewallin/allantools#89]
It is probably time for a new release (see #88) - sometime towards the end of July 2019.
This issue is to discuss what we want to include (or not) before the release.

@aewallin to-do list

- [x] recall and document the release-process on github/pypi
- [x] add real-time ADEV (etc.) functions that operate on a stream of samples.
- [x] readthedocs build fixed (was not updated in 4 months or so..)

issues (to be) fixed:

- [x] #88 pypi install broken for python3(?)
- [x] #70 kw-args for Plot()
- [x] #74 length of noise.Pink()
- [x] #21 mtotdev() htotdev() are very slow
- [x] #51 enabled cs-dataset test again. it is quite slow but maybe it's OK anyway.
- [x] #82 mtie() consumes too much memory

General to-do list:

- [x] #97 save dataset results to file
- [x] ~~decide on datetime functionality~~ (#87) - leaving them out - add documentation on different datetime alternatives
- [x] improve documentation (e.g. #55)

please add your ideas/comments/to-do-lists below - thanks.

**Comment by ffrank14** [comment]
Hi Anders,

idea maybe: make the /frequency2phase()/ function capable of handling 
data with holes (represented by NaN).

F.

Le 03/07/2019 à 18:53, Anders Wallin a écrit :

**Comment by aewallin** [comment]
> idea maybe: make the /frequency2phase()/ function capable of handling data with holes (represented by NaN).

Do you have a particular paper/reference in mind for different ways of handling this? It seems there are many ways: just ignoring gaps, filling them with a linear interpolation between existing datapoints, filling them with some noise model estimated from valid datapoints, etc.

**Comment by yxie-git** [comment]
I agree with @ffrank14. Maybe the input can be in two columns: MJD and data, and then the frequency2phase() function can detect gaps. Stable32 gives several ways to deal with these gaps: e.g. gaps are ignored in ADEV, while gaps are filled in MDEV. But I found an issue: when processing data with gaps, the ADEV results are worse (ADEV values are larger) in the case of firstly freq2phase conversion than direct calculation on phase data. That might be related to the gaps ignorance. If this issue can be improved, that would be nice.

**Comment by yxie-git** [comment]
I agree with @ffrank14. Maybe the input can be in two columns: MJD and data, and then the frequency2phase()/phase2frequency() function can detect gaps. Stable32 gives several ways to deal with these gaps: e.g. gaps are ignored in ADEV, while gaps are filled in MDEV. But I found an issue: when processing data with gaps, the ADEV results are worse (ADEV values are larger) in the case of firstly phase2freq conversion than direct calculation on phase data. That might be related to the gaps ignorance. If this issue can be improved, that would be nice.

**Comment by aewallin** [comment]
2019.07.rc1 is now tagged and uploaded to pypi:
https://pypi.org/project/AllanTools/2019.7rc1/

the instructions say to test with "pip install AllanTools==2019.7rc1"

If you could please test within one week and report any potential problems - thanks!

**Comment by aewallin** [comment]
Things that we did not have time to fix for this release are now moved to #101 

I plan to tag the 2019.07 release on about August 4th

**Comment by fmeynadier** [comment]
FWIW: installs smoothly on a win10  / python 3.6.6 environment I don't usually use for development.
However one of the tests fails: write_results in test_dataset.py. 

     PermissionError: [Errno 13] Permission denied: 'C:\\Users\\FREDER~1.MEY\\AppData\\Local\\Temp\\tmpybjzk6hn'


The function itself works if you use it as intended, I think it is just an issue with Windows handling the temporary file creation in the test.

**Comment by aewallin** [comment]
seems that unix and win work a bit different, google finds this:
https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file

it should be possible to get travis to run the tests under windows (and mac
osx) - that would catch things like this..

**Comment by aewallin** [comment]
#102 is now some (initial) steps towards getting travis to test on OSX and WIN also.

**Comment by aewallin** [comment]
@fmeynadier travis now catches the problem with tempfile on windows, see #103

**Comment by aewallin** [comment]
2019.07 now released, further discussion of new features at #101 
closing this issue.
